### PR TITLE
Hook up fee estimation to transaction creation.

### LINKED ISSUE #10: Creating transactions must use fee estimation
The fee estimation code has already been merged. It just needs to be used each time the pending outputs are changed in the create transaction view.

### LINKED ISSUE #11: Create transaction button should be disabled when there is insufficient input value available
Clicking this button will open the passphrase prompt to sign the transaction even when we know the transaction will not be valid.

### PR DESCRIPTION
**Pull request by jrick**
This change requires a newer version of the wallet's RPC API.

Fixes #10.
Fixes #11.

### CODE REVIEW

**Comment by marcopeereboom** [comment]
exception_during_signing

Two issues; you see Estimated Remaining Balance at 1.0, should be 0. And the crash of course

**Comment by jrick** [comment]
If priority checks were run at all that means the fee was not high enough.  I'll look through it for bugs.

**Comment by marcopeereboom** [comment]
another_exception

**Comment by jrick** [comment]
Rebased over master and fixed a magnitude error with the default fee.  Shouldn't see any more tx rejected errors for low priority.

**Comment by marcopeereboom** [comment]
no_update

**Comment by jrick** [comment]
Coins were unconfirmed, and therefore not usable to fund a transaction.  The same transaction went through after change received the required number of block confirmations.  We should display the spendable balance next to the selected account, instead of the user relying on the total balance of all accounts in the corner.

**Comment by marcopeereboom** [comment]
so I am ok with this going in.  It isn't perfect but certainly works much better.

**Comment by jrick** [comment]
just fixing up an issue in the transaction authoring code where it could create dust change outputs.  Will merge after that is fixed.

**Pull request merged**
