### PR TITLE
Logo removal, UI tweaks, and application icon

### LINKED ISSUE #92: Strip logos until consensus about display and format is reached
The logos are currently in raster format and a final decision about the placement and size of the logos has yet to be made. In the meantime, the logos should be stripped and replaced instead with "Paymetheus" in the title bar and the Decred logo as the icon.

### PR DESCRIPTION
**Pull request by cjepson**
The logos have been removed from Paymetheus until consensus is
reached about their usage, placement, and data types. The UI has
been tweaked to add user-friendly titles to each view, and the
views and the information they contain organized for clarity.
An application icon was also added, making the program easy to
identify from the task bar.

Fixes #92.

### CODE REVIEW

**Comment by marcopeereboom** [comment]
Doesn't compile:

Severity    Code    Description Project File    Line    Suppression State
Error       File 'dcr_logo_2.ico' cannot be found.  Paymetheus

**Comment by marcopeereboom** [comment]
tOK

**Comment by jrick** [comment]
image

For this view, the right edge of the confirm button needs to be horizontally aligned with the text box.

There is also an issue where the text box does not have the same background as the rectangle or border it is in, and there is padding on the left and right side, but no padding on the top and bottom.

I don't care for the giant centered text headers.  I would prefer them to be left aligned and a bit smaller.  In the case of the seed backup confirmation prompt, we already have a header in the style that I like.

Another issue (not due to your branch) is that because all of these prompts are centered, the header text and the buttons at the bottom keep changing vertical positions as you continue through the prompts.  This is one case where it would make sense to hardcode the sizes.

I don't see the new icon used in either the window titlebar or the taskbar.

Was the addition of the bottom-right window resizer corner intentional? I feel that we don't want this because it conflicts with the views: 

image

**Comment by marcopeereboom** [comment]
I had not seen the resize widget.  Has that been removed?

**Comment by cjepson** [comment]
All issues should now be fixed, notably
1. All views are centered properly.
2. Header text is left aligned and smaller.
3. The tab to resize on the bottom right is removed.
4. The radio buttons and "Restore from Seed" feature, not working, have been hidden.
5. All buttons are capitalized.

It is squashed and ready to merge.

**Comment by marcopeereboom** [comment]
tOK

**Comment by jrick** [comment]
As mentioned above, there needs to be some vertical padding between the textbox and border in the seed confirmation view.  It should be equal to the padding on the left and right sides.

It also has a different background color than the border, and needs to be same or transparent.

This PR has my ok after those two issues are resolved.

**Pull request merged**
