### PR TITLE
Add seed restoring option when no wallet is detected.

### LINKED ISSUE #158: Reintroduce seed restoring
This feature was removed before the 0.2.0 release due to it being untested and known issues with Paymetheus during rescans.  It needs to be added back so that both seeds can be imported from other wallets, as well as restores done using a Paymetheus seed backup (otherwise there is no point to forcing the user to make a backup).

### PR DESCRIPTION
**Pull request by jrick**
Closes #158.

### CODE REVIEW

**Comment by jrick** [comment]
This only adds the seed restoring functionality.  The user interface still needs a lot of love before we release.  There is currently no indication of what the wallet is doing while it is restoring (it just sits at the "Encrypt wallet" dialog for several minutes after clicking the encrypt button).

**Review by davecgh — APPROVED** [review]
I have not tested it, but the code changes read well.

Untested OK

**Comment by jrick** [comment]
There's something weird going on with restores.  The restore works fine but then as the next block is attached, all transactions picked up by the restore are duplicated (throwing balances off too).  This is a PM or notification issue.  Restarting PM removes the duplicates.

edit: this if fixed in dcrwallet gRPC API version 3.0.1.

**Comment by jrick** [comment]
A new view has been added after the "encrypt wallet" dialog to show seed restore progress.  During the rescan portion a progress bar is shown with the overall completion of the rescan.

This latest commit also introduced a hang during clean shutdown, and appears to be related to an issue canceling all active RPCs.  Unsure how this was added, but obviously that must be fixed before this is merged.

**Comment by jrick** [comment]
The shutdown hang should be resolved now.  @marcopeereboom this is ready for review

**Review by marcopeereboom — APPROVED** [review]
Tested it and it works like a champ.  Nice touch by making it look like windows update.

**Pull request merged**
